- hosts: local
  remote_user: root
  tasks:
    - name: Install snapd
      apt_rpm:
        name: snapd
        state: present
        update_cache: yes

    - name: Start snapd.socket
      systemd:
        name: snapd.socket
        state: started
        enabled: yes

    - name: Add snap binary path to the system environment
      lineinfile:
        path: /etc/profile
        line: 'export PATH="/var/lib/snapd/snap/bin:$PATH"'
        create: yes

    - name: Install pgAdmin4 using snap
      command: snap install pgadmin4

    - name: Install postgresql-server
      apt_rpm:
        name: postgresql16-server
        state: present
        update_cache: yes

    - name: Init system database for PostgreSQL
      command: /etc/init.d/postgresql initdb

    - name: Start and enable postgresql service
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Install MySQL-server
      apt_rpm:
        name: MySQL-server
        state: present
        update_cache: yes

    - name: Start and enable mysqld service
      systemd:
        name: mysqld
        state: started
        enabled: yes
