name: Test Ansible Playbook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub Actions не поддерживает ALT Linux, поэтому можно использовать контейнер

    container:
      image: alt:latest  # Используем официальный контейнер ALT Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          apt-get update
          apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini install_snap_pgadmin.yml
